services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./DockerFile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
    - ze_bridge

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - GATEWAY_PORT=3001
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - user
      - product
    networks:
    - ze_bridge

  user:
    build: 
      context: ./user
      dockerfile: ./DockerFile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=sDeZHsH33*
      - JWT_EXPIRES_IN=3h
    volumes:
      - ./user:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
    - ze_bridge

  product:
    build: 
      context: ./product
      dockerfile: ./DockerFile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=sDeZHsH33*
    volumes:
      - ./product:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
    - ze_bridge

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ze_bridge

volumes:
  mongo-data:

networks:
  ze_bridge:
    driver: bridge